include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable rules that are too strict for development
    avoid_print: false
    use_key_in_widget_constructors: false
    constant_identifier_names: false
    unnecessary_overrides: false
    empty_catches: false

    avoid_returning_null_for_void: true
    unnecessary_brace_in_string_interps: true
    unnecessary_to_list_in_spreads: true
    use_super_parameters: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:

    unused_local_variable: info
    unused_catch_stack: info
    deprecated_member_use: info
    avoid_returning_null_for_void: info
    unnecessary_brace_in_string_interps: info
    unnecessary_to_list_in_spreads: info